# Generated by Django 6.1.1 on 2026-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dish_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='sweet_level',
            field=models.IntegerField(default=0),
        ),
    ]
