# Generated by Django 6.1.1 on 2026-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dish_sweet_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(db_index=True, help_text='Price in paise'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='spice_level',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sweet_level',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
