import random
from django.core.management.base import BaseCommand
from api.models import Restaurant, Category, Dish

class Command(BaseCommand):
    help = 'Seed the database with 35+ realistic dishes'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding data...')
        
        # Create a restaurant
        restaurant, _ = Restaurant.objects.get_or_create(
            name="The Spice Route",
            defaults={"area": "Downtown", "is_verified": True}
        )

        # Create categories
        categories = ["Appetizers", "Mains", "Desserts", "Beverages", "Sides"]
        cat_objs = {}
        for c in categories:
            cat_objs[c], _ = Category.objects.get_or_create(name=c)

        # 35+ Dishes Data
        dishes_data = [
            # Main Courses
            {
                "name": "Grilled Lemon Herb Salmon",
                "category": cat_objs["Mains"],
                "price": 120000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Grilled+Salmon",
                "ingredients": ["Salmon", "Lemon", "Garlic", "Rosemary", "Olive Oil"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["pescatarian", "gluten-free", "dairy-free"],
                "spice_level": 1,
                "sweet_level": 0,
                "calories": 450,
                "protein": 40,
                "carbs": 5,
                "fat": 25,
                "cuisine": "Continental",
                "is_healthy": True
            },
            {
                "name": "Spicy Thai Green Curry",
                "category": cat_objs["Mains"],
                "price": 95000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Green+Curry",
                "ingredients": ["Chicken", "Coconut Milk", "Green Curry Paste", "Bamboo Shoots", "Basil"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["dairy-free", "gluten-free"],
                "spice_level": 4,
                "sweet_level": 1,
                "calories": 600,
                "protein": 30,
                "carbs": 15,
                "fat": 45,
                "cuisine": "Thai",
                "is_healthy": False
            },
            {
                "name": "Vegan Lentil Shepherd's Pie",
                "category": cat_objs["Mains"],
                "price": 85000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Shepherds+Pie",
                "ingredients": ["Lentils", "Potatoes", "Carrots", "Peas", "Onions", "Olive Oil"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 1,
                "sweet_level": 0,
                "calories": 380,
                "protein": 18,
                "carbs": 55,
                "fat": 8,
                "cuisine": "British",
                "is_healthy": True
            },
            {
                "name": "Classic Beef Bolognese",
                "category": cat_objs["Mains"],
                "price": 110000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Beef+Bolognese",
                "ingredients": ["Ground Beef", "Tomatoes", "Onions", "Garlic", "Spaghetti", "Parmesan"],
                "ingredients_to_avoid": ["Dairy", "Gluten"],
                "dietary_tags": [],
                "spice_level": 1,
                "sweet_level": 1,
                "calories": 750,
                "protein": 35,
                "carbs": 80,
                "fat": 28,
                "cuisine": "Italian",
                "is_healthy": False
            },
            {
                "name": "Paneer Butter Masala",
                "category": cat_objs["Mains"],
                "price": 75000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Paneer+Butter+Masala",
                "ingredients": ["Paneer", "Tomatoes", "Cream", "Butter", "Cashews", "Garam Masala"],
                "ingredients_to_avoid": ["Dairy", "Nuts"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 2,
                "sweet_level": 2,
                "calories": 650,
                "protein": 22,
                "carbs": 20,
                "fat": 55,
                "cuisine": "Indian",
                "is_healthy": False
            },
            {
                "name": "Avocado & Quinoa Salad",
                "category": cat_objs["Mains"],
                "price": 80000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Quinoa+Salad",
                "ingredients": ["Quinoa", "Avocado", "Cherry Tomatoes", "Cucumber", "Lemon Dressing"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 420,
                "protein": 12,
                "carbs": 45,
                "fat": 22,
                "cuisine": "Continental",
                "is_healthy": True
            },
            {
                "name": "Chicken Tikka Masala",
                "category": cat_objs["Mains"],
                "price": 85000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Chicken+Tikka+Masala",
                "ingredients": ["Chicken", "Yogurt", "Tomatoes", "Cream", "Spices"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["gluten-free"],
                "spice_level": 3,
                "sweet_level": 1,
                "calories": 580,
                "protein": 35,
                "carbs": 15,
                "fat": 40,
                "cuisine": "Indian",
                "is_healthy": False
            },
            {
                "name": "Mushroom Risotto",
                "category": cat_objs["Mains"],
                "price": 90000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Mushroom+Risotto",
                "ingredients": ["Arborio Rice", "Mushrooms", "Vegetable Broth", "Parmesan", "Butter", "White Wine"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 520,
                "protein": 14,
                "carbs": 65,
                "fat": 20,
                "cuisine": "Italian",
                "is_healthy": False
            },
            {
                "name": "Pad Thai Noodles",
                "category": cat_objs["Mains"],
                "price": 85000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Pad+Thai",
                "ingredients": ["Rice Noodles", "Tofu", "Shrimp", "Peanuts", "Bean Sprouts", "Tamarind"],
                "ingredients_to_avoid": ["Peanut", "Seafood"],
                "dietary_tags": ["dairy-free", "gluten-free"],
                "spice_level": 2,
                "sweet_level": 2,
                "calories": 600,
                "protein": 25,
                "carbs": 80,
                "fat": 18,
                "cuisine": "Thai",
                "is_healthy": False
            },
            {
                "name": "Beef Stir Fry with Broccoli",
                "category": cat_objs["Mains"],
                "price": 95000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Beef+Stir+Fry",
                "ingredients": ["Beef Slices", "Broccoli", "Soy Sauce", "Ginger", "Garlic", "Sesame Oil"],
                "ingredients_to_avoid": ["Soy", "Gluten"],
                "dietary_tags": ["dairy-free"],
                "spice_level": 1,
                "sweet_level": 1,
                "calories": 480,
                "protein": 40,
                "carbs": 15,
                "fat": 28,
                "cuisine": "Chinese",
                "is_healthy": True
            },
            {
                "name": "Margherita Pizza",
                "category": cat_objs["Mains"],
                "price": 70000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Margherita",
                "ingredients": ["Pizza Dough", "Tomato Sauce", "Fresh Mozzarella", "Basil"],
                "ingredients_to_avoid": ["Dairy", "Gluten"],
                "dietary_tags": ["vegetarian"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 800,
                "protein": 30,
                "carbs": 100,
                "fat": 30,
                "cuisine": "Italian",
                "is_healthy": False
            },
            {
                "name": "Falafel Wrap",
                "category": cat_objs["Mains"],
                "price": 60000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Falafel",
                "ingredients": ["Falafel", "Pita Bread", "Hummus", "Lettuce", "Tomatoes", "Tahini"],
                "ingredients_to_avoid": ["Gluten", "Sesame"],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free"],
                "spice_level": 1,
                "sweet_level": 0,
                "calories": 550,
                "protein": 18,
                "carbs": 70,
                "fat": 20,
                "cuisine": "Middle Eastern",
                "is_healthy": True
            },
            {
                "name": "Palak Paneer",
                "category": cat_objs["Mains"],
                "price": 75000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Palak+Paneer",
                "ingredients": ["Spinach", "Paneer", "Garlic", "Ginger", "Cream"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 2,
                "sweet_level": 0,
                "calories": 450,
                "protein": 20,
                "carbs": 15,
                "fat": 35,
                "cuisine": "Indian",
                "is_healthy": True
            },
            {
                "name": "Chicken Shawarma",
                "category": cat_objs["Mains"],
                "price": 70000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Shawarma",
                "ingredients": ["Marinated Chicken", "Pita Bread", "Garlic Sauce", "Pickles"],
                "ingredients_to_avoid": ["Gluten", "Dairy"],
                "dietary_tags": [],
                "spice_level": 2,
                "sweet_level": 0,
                "calories": 650,
                "protein": 40,
                "carbs": 55,
                "fat": 25,
                "cuisine": "Middle Eastern",
                "is_healthy": False
            },
            {
                "name": "Eggplant Parmesan",
                "category": cat_objs["Mains"],
                "price": 85000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Eggplant+Parm",
                "ingredients": ["Eggplant", "Breadcrumbs", "Tomato Sauce", "Mozzarella", "Parmesan"],
                "ingredients_to_avoid": ["Dairy", "Gluten"],
                "dietary_tags": ["vegetarian"],
                "spice_level": 1,
                "sweet_level": 1,
                "calories": 500,
                "protein": 25,
                "carbs": 50,
                "fat": 20,
                "cuisine": "Italian",
                "is_healthy": False
            },
            {
                "name": "Tom Yum Soup",
                "category": cat_objs["Appetizers"],
                "price": 50000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Tom+Yum",
                "ingredients": ["Shrimp", "Mushrooms", "Lemongrass", "Galangal", "Lime Leaves", "Chili"],
                "ingredients_to_avoid": ["Seafood"],
                "dietary_tags": ["dairy-free", "gluten-free", "pescatarian"],
                "spice_level": 4,
                "sweet_level": 1,
                "calories": 150,
                "protein": 15,
                "carbs": 10,
                "fat": 5,
                "cuisine": "Thai",
                "is_healthy": True
            },
            {
                "name": "Caprese Salad",
                "category": cat_objs["Appetizers"],
                "price": 60000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Caprese",
                "ingredients": ["Fresh Mozzarella", "Tomatoes", "Basil", "Balsamic Glaze", "Olive Oil"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 1,
                "calories": 300,
                "protein": 15,
                "carbs": 10,
                "fat": 22,
                "cuisine": "Italian",
                "is_healthy": True
            },
            {
                "name": "Vegetable Spring Rolls",
                "category": cat_objs["Appetizers"],
                "price": 45000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Spring+Rolls",
                "ingredients": ["Cabbage", "Carrots", "Glass Noodles", "Spring Roll Wrapper", "Sweet Chili Sauce"],
                "ingredients_to_avoid": ["Gluten", "Soy"],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free"],
                "spice_level": 1,
                "sweet_level": 2,
                "calories": 250,
                "protein": 5,
                "carbs": 35,
                "fat": 10,
                "cuisine": "Chinese",
                "is_healthy": False
            },
            {
                "name": "Chicken 65",
                "category": cat_objs["Appetizers"],
                "price": 65000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Chicken+65",
                "ingredients": ["Chicken", "Yogurt", "Curry Leaves", "Chili Powder", "Rice Flour"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["gluten-free"],
                "spice_level": 4,
                "sweet_level": 0,
                "calories": 400,
                "protein": 25,
                "carbs": 15,
                "fat": 25,
                "cuisine": "Indian",
                "is_healthy": False
            },
            {
                "name": "Edamame",
                "category": cat_objs["Appetizers"],
                "price": 35000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Edamame",
                "ingredients": ["Edamame Beans", "Sea Salt"],
                "ingredients_to_avoid": ["Soy"],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 120,
                "protein": 11,
                "carbs": 9,
                "fat": 5,
                "cuisine": "Japanese",
                "is_healthy": True
            },
            {
                "name": "Tiramisu",
                "category": cat_objs["Desserts"],
                "price": 55000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Tiramisu",
                "ingredients": ["Mascarpone Cheese", "Espresso", "Ladyfingers", "Cocoa Powder", "Eggs", "Sugar"],
                "ingredients_to_avoid": ["Dairy", "Gluten", "Egg"],
                "dietary_tags": ["vegetarian"],
                "spice_level": 0,
                "sweet_level": 4,
                "calories": 450,
                "protein": 8,
                "carbs": 40,
                "fat": 28,
                "cuisine": "Italian",
                "is_healthy": False
            },
            {
                "name": "Gulab Jamun",
                "category": cat_objs["Desserts"],
                "price": 40000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Gulab+Jamun",
                "ingredients": ["Milk Powder", "Flour", "Sugar Syrup", "Rose Water", "Cardamom"],
                "ingredients_to_avoid": ["Dairy", "Gluten"],
                "dietary_tags": ["vegetarian"],
                "spice_level": 0,
                "sweet_level": 5,
                "calories": 300,
                "protein": 5,
                "carbs": 50,
                "fat": 10,
                "cuisine": "Indian",
                "is_healthy": False
            },
            {
                "name": "Matcha Ice Cream",
                "category": cat_objs["Desserts"],
                "price": 45000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Matcha+Ice+Cream",
                "ingredients": ["Milk", "Cream", "Sugar", "Matcha Powder", "Egg Yolks"],
                "ingredients_to_avoid": ["Dairy", "Egg"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 3,
                "calories": 250,
                "protein": 4,
                "carbs": 25,
                "fat": 15,
                "cuisine": "Japanese",
                "is_healthy": False
            },
            {
                "name": "Vegan Brownie",
                "category": cat_objs["Desserts"],
                "price": 50000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Vegan+Brownie",
                "ingredients": ["Flour", "Cocoa Powder", "Almond Milk", "Coconut Oil", "Sugar", "Walnuts"],
                "ingredients_to_avoid": ["Gluten", "Nuts"],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free"],
                "spice_level": 0,
                "sweet_level": 4,
                "calories": 350,
                "protein": 5,
                "carbs": 45,
                "fat": 18,
                "cuisine": "American",
                "is_healthy": False
            },
            {
                "name": "Mango Sorbet",
                "category": cat_objs["Desserts"],
                "price": 35000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Mango+Sorbet",
                "ingredients": ["Mango Puree", "Water", "Sugar", "Lemon Juice"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 3,
                "calories": 150,
                "protein": 1,
                "carbs": 38,
                "fat": 0,
                "cuisine": "Continental",
                "is_healthy": True
            },
            {
                "name": "Mango Lassi",
                "category": cat_objs["Beverages"],
                "price": 30000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Mango+Lassi",
                "ingredients": ["Mango", "Yogurt", "Milk", "Sugar", "Cardamom"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 3,
                "calories": 200,
                "protein": 8,
                "carbs": 30,
                "fat": 5,
                "cuisine": "Indian",
                "is_healthy": True
            },
            {
                "name": "Masala Chai",
                "category": cat_objs["Beverages"],
                "price": 20000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Masala+Chai",
                "ingredients": ["Black Tea", "Milk", "Ginger", "Cardamom", "Cloves", "Sugar"],
                "ingredients_to_avoid": ["Dairy"],
                "dietary_tags": ["vegetarian", "gluten-free"],
                "spice_level": 1,
                "sweet_level": 2,
                "calories": 100,
                "protein": 4,
                "carbs": 12,
                "fat": 4,
                "cuisine": "Indian",
                "is_healthy": True
            },
            {
                "name": "Iced Americano",
                "category": cat_objs["Beverages"],
                "price": 25000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Iced+Americano",
                "ingredients": ["Espresso", "Water", "Ice"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 5,
                "protein": 0,
                "carbs": 1,
                "fat": 0,
                "cuisine": "Continental",
                "is_healthy": True
            },
            {
                "name": "Green Smoothie",
                "category": cat_objs["Beverages"],
                "price": 40000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Green+Smoothie",
                "ingredients": ["Spinach", "Kale", "Apple", "Banana", "Almond Milk"],
                "ingredients_to_avoid": ["Nuts"],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 2,
                "calories": 180,
                "protein": 4,
                "carbs": 35,
                "fat": 3,
                "cuisine": "Continental",
                "is_healthy": True
            },
            {
                "name": "Pina Colada (Virgin)",
                "category": cat_objs["Beverages"],
                "price": 45000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Pina+Colada",
                "ingredients": ["Pineapple Juice", "Coconut Cream", "Ice"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 4,
                "calories": 250,
                "protein": 1,
                "carbs": 45,
                "fat": 8,
                "cuisine": "Continental",
                "is_healthy": False
            },
            {
                "name": "Garlic Naan",
                "category": cat_objs["Sides"],
                "price": 25000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Garlic+Naan",
                "ingredients": ["Flour", "Garlic", "Butter", "Yeast", "Yogurt"],
                "ingredients_to_avoid": ["Gluten", "Dairy"],
                "dietary_tags": ["vegetarian"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 200,
                "protein": 5,
                "carbs": 30,
                "fat": 8,
                "cuisine": "Indian",
                "is_healthy": False
            },
            {
                "name": "French Fries",
                "category": cat_objs["Sides"],
                "price": 30000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=French+Fries",
                "ingredients": ["Potatoes", "Vegetable Oil", "Salt"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 365,
                "protein": 4,
                "carbs": 48,
                "fat": 17,
                "cuisine": "American",
                "is_healthy": False
            },
            {
                "name": "Steamed Rice",
                "category": cat_objs["Sides"],
                "price": 15000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Steamed+Rice",
                "ingredients": ["Jasmine Rice", "Water"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 205,
                "protein": 4,
                "carbs": 45,
                "fat": 0,
                "cuisine": "Asian",
                "is_healthy": True
            },
            {
                "name": "Side Salad",
                "category": cat_objs["Sides"],
                "price": 25000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Side+Salad",
                "ingredients": ["Mixed Greens", "Tomatoes", "Cucumbers", "Vinaigrette"],
                "ingredients_to_avoid": [],
                "dietary_tags": ["vegan", "vegetarian", "dairy-free", "gluten-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 50,
                "protein": 1,
                "carbs": 5,
                "fat": 3,
                "cuisine": "Continental",
                "is_healthy": True
            },
            {
                "name": "Onion Rings",
                "category": cat_objs["Sides"],
                "price": 35000,
                "image_url": "https://placehold.co/600x400/e2e8f0/475569?text=Onion+Rings",
                "ingredients": ["Onions", "Batter", "Vegetable Oil", "Salt"],
                "ingredients_to_avoid": ["Gluten"],
                "dietary_tags": ["vegetarian", "dairy-free"],
                "spice_level": 0,
                "sweet_level": 0,
                "calories": 400,
                "protein": 4,
                "carbs": 45,
                "fat": 22,
                "cuisine": "American",
                "is_healthy": False
            }
        ]

        for data in dishes_data:
            Dish.objects.update_or_create(
                name=data['name'],
                restaurant=restaurant,
                defaults=data
            )
        
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(dishes_data)} dishes.'))
